# TODO Remove before pr
on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: flake8 . --isolated --exclude=.cache,.venv,.svn,CVS,.bzr,.hg,.git,__pycache__,.tox --max-line-length=119
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: optimum-surface-285007
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_DEPLOY_KEY }}
        with:
          args: builds submit lumpy-llamas/ --config lumpy-llamas/cloudbuild.yml
      - name: deploy
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: optimum-surface-285007
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_DEPLOY_KEY }}
        with:
          args: run deploy llamma --image eu.gcr.io/optimum-surface-285007/llammabbs --platform managed --region europe-west1 --quiet
